# -*- coding: utf-8 -*-
"""SCA - Hoang - ETL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ciyhHlerKPY3DMGYNVX62pakmfYJ_N_W
"""

# import libraries
import pandas as pd

"""####**Extract**

**1. Enrollies' data**
"""

url = 'https://docs.google.com/spreadsheets/d/1VCkHwBjJGRJ21asd9pxW4_0z2PWuKhbLR3gUHm-p4GI/export?format=xlsx'

enrollies_data = pd.read_excel(url)

enrollies_data.head()

enrollies_data.info()

"""**2. Enrollies' education**"""

enrollies_edu = pd.read_excel('enrollies_education.xlsx')

enrollies_edu.head()

enrollies_edu.info()

"""**3. Enrollies' working experience**

"""

enrollies_work = pd.read_csv('work_experience.csv')

enrollies_work.head()

"""**4. Training hours**"""

!pip install pymysql

from sqlalchemy import create_engine
import pymysql

engine = create_engine('mysql+pymysql://etl_practice:550814@112.213.86.31:3360/company_course')

training_hours = pd.read_sql_table('training_hours', con=engine)

training_hours.head()

"""**5. City development index**"""

web_table = pd.read_html('https://sca-programming-school.github.io/city_development_index/index.html')

CDI = web_table[0]

CDI.head()

"""**6. Employment**"""

employment = pd.read_sql_table('employment', con=engine)

employment.head()

"""####**Transform**

**1. Enrollies' data**
"""

enrollies_data.info()

# convert data type
enrollies_data = enrollies_data.convert_dtypes()

enrollies_data['gender'] = enrollies_data['gender'].fillna(enrollies_data['gender'].mode()[0])

enrollies_data.info()

"""**2. Enrollies' education**"""

enrollies_edu.info()

enrollies_edu['education_level'].unique()

enrollies_edu['enrolled_university'].unique()

enrollies_edu['major_discipline'].unique()

enrollies_edu = enrollies_edu.convert_dtypes()

# fill missing value
enroll_list = ['education_level', 'enrolled_university', 'major_discipline']
for i in enroll_list:
  enrollies_edu[i] = enrollies_edu[i].fillna(enrollies_edu[i].mode()[0])

enrollies_edu.info()

"""**3. Enrollies' working experience**

"""

enrollies_work.info()

enrollies_work['experience'].unique()

enrollies_work['company_size'].unique()

enrollies_work['company_type'].unique()

enrollies_work['last_new_job'].unique()

enrollies_work = enrollies_work.convert_dtypes()

# fill missing value
enrollies_work['company_size'] = enrollies_work['company_size'].fillna('Unknown')
enrollies_work['company_type'] = enrollies_work['company_type'].fillna('Unknown')
enrollies_work['experience'] = enrollies_work['experience'].fillna(enrollies_work['experience'].mode()[0])
enrollies_work['last_new_job'] = enrollies_work['last_new_job'].fillna(enrollies_work['last_new_job'].mode()[0])

enrollies_work.info()

"""**4. Training hours**

"""

training_hours.info()

"""**5. City development index**

"""

CDI.info()

"""**6. Employment**

"""

employment.info()

"""####**Load**"""

# Path to SQLIte database
db_path = 'data_warehouse.db'

# Create an SQLAlchemy engine
warehouse_engine = create_engine(f'sqlite:///{db_path}')

# Write DataFrames to database
enrollies_data.to_sql('enrollies_data', con=warehouse_engine, if_exists='replace', index=False)
enrollies_edu.to_sql('enrollies_edu', con=warehouse_engine, if_exists='replace', index=False)
enrollies_work.to_sql('enrollies_work', con=warehouse_engine, if_exists='replace', index=False)
training_hours.to_sql('training_hours', con=warehouse_engine, if_exists='replace', index=False)
CDI.to_sql('CDI', con=warehouse_engine, if_exists='replace', index=False)
employment.to_sql('employment', con=warehouse_engine, if_exists='replace', index=False)